;;; Program for printing integer between 0 and 39 in Roman numeral representation
(defun roman-system (x)
  (cond ((null x) (format t "~&Enter a number: ") (roman-system (read)))
	((> x 39) (format t "~&Number too big!") (roman-system nil))
	((> x 9) (princ "X") (roman-system (- x 10)))
	((= x 9) (princ "IX") (roman-system 0))
	((> x 4) (princ "V") (roman-system (- x 5)))
	((= x 4) (princ "IV") (roman-system 0))
	((> x 0) (princ "I") (roman-system (- x 1)))
	((= x 0) (if (y-or-n-p "~&Do you want to continue? ")
		     (roman-system nil)
		     nil))))

(defun roman-system.tree (x)
  (cond ((null x) (format t "~&Enter a number: ") (roman-system (read)))
	((> x 39) (format t "~&Number too big!") (roman-system nil))
	(t (if (> x 4)
	       (if (> x 9)
		   (progn (princ "X") (roman-system (- x 10)))
		   (if (= x 9)
		       (progn (princ "IX") (roman-system 0))
		       (progn (princ "V") (roman-system (- x 5)))))
	       (if (= x 4)
		   (progn (princ "IV") (roman-system 0))
		   (if (= x 0)
		       (if (y-or-n-p "~&Do you want to continue? ")
			   (roman-system nil)
			   nil)
		       (progn (princ "I") (roman-system (- x 1)))))))))
